### ISSUE TITLE
Add proxy for git sites

### ISSUE THREAD

**Issue by craftslab** [repo-scm/.github#8]
## Project

- [repo-scm/proxy](https://github.com/repo-scm/proxy)

## Usage

```bash
# Run proxy server
# http://localhost:9090/ui
proxy serve [--address string]

# Query available site
proxy query [--output string] [--verbose]

# List all sites
proxy list
```

## Settings

Settings can be set in the directory `$HOME/.repo-scm/proxy.yaml`.

An example of `$HOME/.repo-scm/proxy.yaml` as below:

```yaml
gerrits:
  - site_name: "your_site"
    api_base: "http://localhost:8080"
    user_name: "your_name"
    user_pass: "your_pass"
```
